name: Run tests
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby_version:
          - 2.4
          - 2.5
          - 2.6
          - 2.7
        rack_version:
          - ~> 1.6
          - ~> 2.0.9
          - ~> 2.1.4
          - ~> 2.2.3

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ${{ matrix.ruby_version }}
      - name: Run tests on ruby ${{ matrix.ruby_version }} with rack ${{ matrix.rack_version }}
        run: |
          bundle check || bundle update
          bundle exec rake
        env:
          RACK_VERSION: ${{ matrix.rack_version }}
